name: "Sync `config.js` to Template Repository"

on:
  workflow_dispatch: { }
  push:
    paths:
      - docs/config.js
      - .github/workflows/sync-config.js.yaml

jobs:
  sync-to-template-repo:
    name: "Sync `config.js` to Template Repository"

    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout Source Repository"
        uses: "actions/checkout@v3"
        with:
          repository: "${{ github.repository }}"
          path: "pn"
          token: ${{ secrets.PAPERPILE_REPO_PAT }}

      - name: "Checkout Template Repository"
        uses: "actions/checkout@v3"
        with:
          repository: "jmuchovej/sync-paperpile-to-notion"
          path: "st"
          token: ${{ secrets.PAPERPILE_REPO_PAT }}

      - name: "Sync `config.js` changes"
        shell: "bash"
        run: |
          cp ./pn/docs/config.js ./st/.config/paperpile-notion/config.js

      - name: "Commit Changes to Template Repository"
        uses: "endbug/add-and-commit@v9"
        with:
          message: "ðŸ”§ Update `config.js` to reflect latest release configuration"
          committer_name: "GitHub Actions"
          committer_email: "actions@github.com"
          cwd: "./st/"
          add: ".config/paperpile-notion/config.js"
